QR_bilet/urls.py
from django.contrib import admin
from django.urls import path, include
from bilets.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('bilets/', include('bilets.urls', namespace='bilets')),
    path('Users/', include('Users.urls', namespace='Users')),
]

Users/urls.py
from django.urls import path
from .views import UserLoginView

app_name = 'Users'

urlpatterns = [
    path('UserLogin/', UserLoginView.as_view(), name='UserLogin'),
]

bilets/urls.py
from django.urls import path
from bilets.views import IndexView, BuyBilets, ProverkaBilets

app_name = 'bilets'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('BuyBilets', BuyBilets.as_view(), name='BuyBilets'),
    path('ProverkaBilets', ProverkaBilets.as_view(), name='ProverkaBilets'),
]

Users/models.py
from django.db import models

# Create your models here.

bilets/models.py
from django.db import models
from django.conf import settings
import uuid


class Bilets(models.Model):
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    invoiceId = models.UUIDField(unique=True, default=uuid.uuid4)


class Proverka(models.Model):
    invoiceId_Vvod = models.UUIDField()

Users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import AbstractUser


class UserLoginForm(AuthenticationForm):
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите email'
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = AbstractUser
        fields = ('email', 'password')




class UserRegistrationForm(UserCreationForm):
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите email'
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Введите пароль'
    }))

    class Meta:
        model = AbstractUser
        fields = ('email', 'password')

bilets/forms.py
from django import forms
from bilets.models import Proverka


class ProverkaForm(forms.Form):
    invoiceId_Vvod = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
    }))

    class Meta:
        model = Proverka
        fields = ('invoiceId_Vvod',)

Users/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from .forms import UserLoginForm
from django.contrib.auth.models import AbstractUser


class UserLoginView(LoginView):
    template_name = 'Users/login.html'
    form_class = UserLoginForm
    title = 'Авторизация'


# class UserRegistration(CreateView):
#     model = AbstractUser

bilets/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from bilets.models import Bilets
from django.core.mail import send_mail
from bilets.forms import ProverkaForm
from django.views import View
import uuid


class IndexView(TemplateView):
    template_name = 'bilets/bilets_index.html'
    title = 'Buy bilets'


class BuyBilets(ListView):
    model = Bilets
    template_name = 'bilets/confirmation.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        new_bilet = Bilets.objects.create(user=self.request.user, invoiceId=uuid.uuid4())
        self.send_email_notification(new_bilet)
        latest_bilet = Bilets.objects.filter(user=self.request.user).last()
        return [latest_bilet]


    def send_email_notification(self, bilet):
        subject = 'Успешная покупка билета'
        message = f'Вы успешно купили билет с номером {bilet.invoiceId}. Билет был отправлен на вашу почту.'
        from_email = 'olezkayou.2@gmail.com'
        recipient_list = [bilet.user.email]
        send_mail(subject, message, from_email, recipient_list)


class ProverkaBilets(View):
    template_name = 'bilets/check_ticket.html'
    form_class = ProverkaForm

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'is_valid_ticket': None})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                invoice_id_vvod = form.cleaned_data['invoiceId_Vvod']
                bilet = Bilets.objects.get(invoiceId=invoice_id_vvod)
                return render(request, self.template_name, {'form': form, 'is_valid_ticket': True, 'bilet': bilet})

            except Bilets.DoesNotExist:
                return render(request, self.template_name, {'form': form, 'is_valid_ticket': False, 'bilet': None})

        return render(request, self.template_name, {'form': form, 'is_valid_ticket': None, 'bilet': None})

Users/templates/Users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <div>
            <a href="{% url 'bilets:index' %}" class="button">На главную</a> |
            <a href="registration.html" class="button">Регистрация</a>
        </div>
    </header>

    <main>
        <div class="login-container" style="margin-top: 30px;">
            <h2>Авторизация</h2>
            <form action="{% url 'Users:UserLogin' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password.id_for_label }}">
                        Пароль
                    </label>
                    {{ form.password }}
                </div>
                <button type="submit" class="button">Войти</button>
            </form>
        </div>
    </main>
</body>
</html>

Users/templates/Users/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="stylesheet" href="{% static 'vendor/css/styles.css' %}">
</head>
<body>
    <header>
        <div>
            <a href="bilets_index.html" class="button">На главную</a> |
            <a href="login.html" class="button">Авторизация</a>
        </div>

    </header>

    <main>
        <div class="registration-container" style="margin-top: 30px;">
            <h2>Регистрация</h2>
            <form>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Пароль:</label>
                    <input type="password" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label for="confirmPassword">Повторите пароль:</label>
                    <input type="password" id="confirmPassword" name="confirmPassword" required>
                </div>
                <button type="submit" class="button">Зарегистрироваться</button>
            </form>
        </div>
    </main>
</body>
</html>

bilets/templates/bilets/bilets_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Пример верстки</title>
    <link rel="stylesheet" href="{% static 'vendor/css/styles.css' %}">
</head>
<body>
    <header>
        <div>
            <a href="registration.html" class="button">Регистрация</a> |
            <a href="{% url 'Users:UserLogin' %}" class="button">Авторизация</a>
        </div>
    </header>

    <main>
        <div class="buttons-container">
            <a href="{% url 'bilets:BuyBilets' %}" class="button">Купить билет</a>
            <a href="{% url 'bilets:ProverkaBilets' %}" class="button">Проверить билет</a>
        </div>
    </main>
</body>
</html>

bilets/templates/bilets/check_ticket.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Проверка билета</title>
    <link rel="stylesheet" href="{% static 'vendor/css/styles.css' %}">
</head>
<body>
    <div class="check-ticket-container">
        <h2>Введите уникальный id билета</h2>
        <form action="{% url 'bilets:ProverkaBilets' %}" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label class="small mb-1" for="{{ form.invoiceId_Vvod.id_for_label }}">ID билета:</label>
                {{ form.invoiceId_Vvod }}
            </div>
            <button type="submit">Проверить билет</button>
        </form>

        <div id="checkResult" class="hidden">
            {% if is_valid_ticket is not None %}
                {% if is_valid_ticket %}
                    <p>Билет действителен</p>
                    {% if bilet %}
                        <p>Данные билета: {{ bilet }}</p>
                    {% endif %}
                {% elif is_valid_ticket == False %}
                    <p>Билет не действителен</p>

                {% endif %}
            {% endif %}
        </div>

        <a href="{% url 'bilets:index' %}" class="button">На главную</a>
    </div>
</body>
</html>

bilets/templates/bilets/confirmation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подтверждение покупки</title>
    <link rel="stylesheet" href="{% static 'vendor/css/styles.css' %}">
</head>
<body>
    <div class="confirmation-container">
        {% for object in object_list %}
            <h2>Вы успешно купили билет с номером: {{ object.invoiceId }}</h2>
        {% endfor %}
        <p>Билет был отправлен на вашу почту! </p>
        <a href="{% url 'bilets:index' %}" class="button">На главную</a>
    </div>
</body>
</html>

bilets/templates/bilets/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Авторизация</title>
    <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <div>
            <a href="{% url 'bilets:index' %}" class="button">На главную</a> |
            <a href="registration.html" class="button">Регистрация</a>
        </div>
    </header>

    <main>
        <div class="login-container" style="margin-top: 30px;">
            <h2>Авторизация</h2>
            <form>
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Email:</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.password.id_for_label }}">
                        Пароль
                    </label>
                    {{ form.password }}
                </div>
                <button type="submit" class="button">Войти</button>
            </form>
        </div>
    </main>
</body>
</html>